services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      cache_from:
        - type=local,src=./.buildcache/backend
      cache_to:
        - type=local,dest=./.buildcache/backend,mode=max
      target: base
    env_file:
      - .env
    environment:
      MONGODB_URI: ${MONGODB_URI}
      KEYCLOAK_BASE_URL: ${KEYCLOAK_BASE_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_ADMIN_CLIENT_ID: ${KEYCLOAK_ADMIN_CLIENT_ID}
      KEYCLOAK_ADMIN_CLIENT_SECRET: ${KEYCLOAK_ADMIN_CLIENT_SECRET}
      GROQ_API_KEY: ${GROQ_API_KEY}
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - type=local,src=./.buildcache/frontend
      cache_to:
        - type=local,dest=./.buildcache/frontend,mode=max
    env_file:
      - .env
    ports:
      - "4900:80"
